### ISSUE TITLE
Incompatible with Building Gadgets

### ISSUE THREAD

**Issue by Kasualix** [Asek3/Connectedness#9]
crash: https://pastebin.ubuntu.com/p/C7QJVJsNqB/

Gadget cannot be rendered correctly.
And when you open the GUI it exists, the game crashes.

Crash happens to other people, I am just a helper submitting issue (and I don't play 1.19.2 very much).

**Comment by Totomio** [comment]
Same for me, opening the building gadget panel with connectedness installed make crashes the game.

**Comment by Random832** [comment]
Secondary issue *also* with building gadgets, having a blank construction block in your inventory or in JEI causes a crash.

```
[16:40:07] [Render thread/ERROR] [ne.mi.cl.gu.ov.ForgeGui/]: Error rendering overlay 'minecraft:hotbar'
net.minecraft.ReportedException: Rendering item
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174235_(ItemRenderer.java:317) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-renderer-indigo.mixins.json:ItemRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174277_(ItemRenderer.java:291) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-renderer-indigo.mixins.json:ItemRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174229_(ItemRenderer.java:287) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-renderer-indigo.mixins.json:ItemRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.Gui.m_168677_(Gui.java:1107) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.Gui.m_93009_(Gui.java:526) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.gui.overlay.VanillaGuiOverlay.lambda$static$5(VanillaGuiOverlay.java:63) ~[forge-1.19.2-43.2.4-universal.jar%23134!/:?] {re:classloading}
	at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:141) ~[forge-1.19.2-43.2.4-universal.jar%23134!/:?] {re:classloading}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%2388!/:?] {}
	at net.minecraftforge.client.gui.overlay.ForgeGui.m_93030_(ForgeGui.java:136) ~[forge-1.19.2-43.2.4-universal.jar%23134!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:876) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.4.jar%23122!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23109!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23109!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23109!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23109!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23109!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23109!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23109!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60815_()" because "mimic" is null
	at com.direwolf20.buildinggadgets.common.blocks.ConstructionBlock.m_7952_(ConstructionBlock.java:193) ~[buildinggadgets-3.16.2-build.22+mc1.19.2.jar%23126!/:3.16.2-build.22+mc1.19.2] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60768_(BlockBehaviour.java:502) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60804_(BlockBehaviour.java:590) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,re:mixin}
	at me.pepperbell.continuity.client.resource.CustomBlockLayers.getLayer(CustomBlockLayers.java:41) ~[connectedness-2.0.1a.jar%23127!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.ItemBlockRenderTypes.handler$zzh000$continuity$onHeadGetBlockLayers(ItemBlockRenderTypes.java:531) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:connectedness.mixins.json:RenderLayersMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemBlockRenderTypes.getRenderLayers(ItemBlockRenderTypes.java) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:connectedness.mixins.json:RenderLayersMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.extensions.IForgeBakedModel.getRenderTypes(IForgeBakedModel.java:86) ~[forge-1.19.2-43.2.4-universal.jar%23134!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.resources.model.SimpleBakedModel.getRenderTypes(SimpleBakedModel.java:89) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.RenderTypeHelper.getFallbackItemRenderType(RenderTypeHelper.java:65) ~[forge-1.19.2-43.2.4-universal.jar%23134!/:?] {re:classloading}
	at net.minecraftforge.client.extensions.IForgeBakedModel.getRenderTypes(IForgeBakedModel.java:101) ~[forge-1.19.2-43.2.4-universal.jar%23134!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.resources.model.SimpleBakedModel.getRenderTypes(SimpleBakedModel.java:101) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115143_(ItemRenderer.java:132) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-renderer-indigo.mixins.json:ItemRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115127_(ItemRenderer.java:259) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-renderer-indigo.mixins.json:ItemRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174235_(ItemRenderer.java:300) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-renderer-indigo.mixins.json:ItemRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	... 39 more
[16:40:07] [Render thread/ERROR] [minecraft/Minecraft]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60815_()" because "mimic" is null
	at com.direwolf20.buildinggadgets.common.blocks.ConstructionBlock.m_7952_(ConstructionBlock.java:193) ~[buildinggadgets-3.16.2-build.22+mc1.19.2.jar%23126!/:3.16.2-build.22+mc1.19.2] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60768_(BlockBehaviour.java:502) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60804_(BlockBehaviour.java:590) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,re:mixin}
	at me.pepperbell.continuity.client.resource.CustomBlockLayers.getLayer(CustomBlockLayers.java:41) ~[connectedness-2.0.1a.jar%23127!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.ItemBlockRenderTypes.handler$zzh000$continuity$onHeadGetBlockLayers(ItemBlockRenderTypes.java:531) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:connectedness.mixins.json:RenderLayersMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemBlockRenderTypes.getRenderLayers(ItemBlockRenderTypes.java) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:connectedness.mixins.json:RenderLayersMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.extensions.IForgeBakedModel.getRenderTypes(IForgeBakedModel.java:86) ~[forge-1.19.2-43.2.4-universal.jar%23134!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.resources.model.SimpleBakedModel.getRenderTypes(SimpleBakedModel.java:89) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.RenderTypeHelper.getFallbackItemRenderType(RenderTypeHelper.java:65) ~[forge-1.19.2-43.2.4-universal.jar%23134!/:?] {re:classloading}
	at net.minecraftforge.client.extensions.IForgeBakedModel.getRenderTypes(IForgeBakedModel.java:101) ~[forge-1.19.2-43.2.4-universal.jar%23134!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.resources.model.SimpleBakedModel.getRenderTypes(SimpleBakedModel.java:101) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115143_(ItemRenderer.java:132) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-renderer-indigo.mixins.json:ItemRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_174242_(ItemRenderer.java:231) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-renderer-indigo.mixins.json:ItemRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109322_(ItemInHandRenderer.java:123) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109371_(ItemInHandRenderer.java:467) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemInHandRenderer.m_109314_(ItemInHandRenderer.java:290) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109120_(GameRenderer.java:783) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1074) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23129!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.4.jar%23122!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23109!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23109!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23109!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23109!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23109!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23109!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23109!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
```

**Comment by Teqed** [comment]
As a temporary work-around, you can use KubeJS to hide `buildinggadgets:construction_block` from JEI so that you don't crash while browsing items, but can still make use of the building gadgets.

For example, create a file in `/.minecraft/kubejs/client_scripts` and name it `jei_hide.js`.
```JS
JEIEvents.hideItems(event => {
  event.hide('buildinggadgets:construction_block')
})
```

This may eventually be solved permanently by https://github.com/Direwolf20-MC/BuildingGadgets/pull/738
